### ISSUE TITLE
Any help needed?

### ISSUE THREAD

**Issue by zdraganov** [AlexCuse/watermill-jetstream#1]
Hello! Do you need any help in a particular direction for the project?

**Comment by AlexCuse** [comment]
@zdraganov always need help I actually was just coming on here to start adding some knowN issues.    Is there anything you especially need to see?  I am targeting relatively low volume services on raspberry pi's and similar right now so there is probably a lot of room to test volume.  Working through the built in test getting feature support sorted mainly so any feature you especially need to use in your apps could be a good place to start too.

**Comment by zdraganov** [comment]
Ok, will jump into more testing and I will see.
