### ISSUE TITLE
Smarter Stream/Consumer Creation 

### ISSUE THREAD

**Issue by AlexCuse** [AlexCuse/watermill-jetstream#2]
Right now the client always checks if the stream is available and creates if needed - I think this should be opt-in behavior.

**Comment by zdraganov** [comment]
I think the auto-stream provisioning could be an optional parameter, rather than forced.
And it depending on that option there should be:
1. Provisioning missing channels on boot
2. Ensure that all channels are provisioned

**Comment by AlexCuse** [comment]
I think it will need to be "lazy" if enabled with the way watermill subscriptions work but it should be easy to make provisioning optional.

**Comment by AlexCuse** [comment]
Keep this in mind https://github.com/nats-io/nats.go/issues/874

**Comment by AlexCuse** [comment]
@zdraganov i made this opt-out through configuration for now.  The underlying nats client mostly supports it (see above issue).  As I work w jetstream more I'm sure I will develop opinions about how to do it better, it's probably a different option for publish than subscribe eventually.
